✨ classic: adds relation initStore
NateTheGreatt/bitECS pull request #144
Opened 2024-06-10 13:36 UTC by pietrovismara

2024-06-10 15:30 UTC, NateTheGreatt requested changes
great work thanks for this! couple change requests

2024-06-10 15:30 UTC, NateTheGreatt commented on packages/classic/src/relation/Relation.ts
>  import { $schema } from '../component/symbols';
```suggestion
```

2024-06-10 15:30 UTC, NateTheGreatt commented on packages/classic/src/relation/types.ts
> +	[$schema]: () => T;
```suggestion
	[$initStore]: () => T;
```

2024-06-10 15:30 UTC, NateTheGreatt commented on packages/classic/src/relation/types.ts
>  import { $schema } from '../component/symbols';
```suggestion
import { $initStore } from '../component/symbols';
```

2024-06-10 15:30 UTC, NateTheGreatt commented on packages/classic/src/relation/Relation.ts
> +	const schema = relation[$schema];
```suggestion
	const initStore = relation[$initStore];
```

2024-06-10 15:30 UTC, NateTheGreatt commented on packages/classic/src/relation/Relation.ts
> +	defineHiddenProperty(relation, $schema, initStore);
```suggestion
	defineHiddenProperty(relation, $initStore, initStore);
```

2024-06-24 22:53 UTC, merged

2024-06-24 22:53 UTC, krispya commented
Looks good to me. I'm merging.